name: Python Fast Api

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tags: 
        description: Manual Run
        required: false

permissions:
  contents: read

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pytest
